// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGXnx_MKtz3jK2rvV8mKxT6ld0oWhYIXM',
    appId: '1:86032851224:web:c77e6a8e0b4b19dc347e6d',
    messagingSenderId: '86032851224',
    projectId: 'movie-ef056',
    authDomain: 'movie-ef056.firebaseapp.com',
    storageBucket: 'movie-ef056.firebasestorage.app',
    measurementId: 'G-MZQ70X1046',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwPoKmQCw1DeGYmbOLDOjNRDXK82LrSec',
    appId: '1:86032851224:android:28909b0dcd003eac347e6d',
    messagingSenderId: '86032851224',
    projectId: 'movie-ef056',
    storageBucket: 'movie-ef056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIimcbUm3_h-LtOwJMFrtYTt9T6MaeuOM',
    appId: '1:86032851224:ios:d51ac4934e64cad9347e6d',
    messagingSenderId: '86032851224',
    projectId: 'movie-ef056',
    storageBucket: 'movie-ef056.firebasestorage.app',
    iosClientId: '86032851224-4mbemm1indckn41s5f3ao62afkbfmlk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIimcbUm3_h-LtOwJMFrtYTt9T6MaeuOM',
    appId: '1:86032851224:ios:d51ac4934e64cad9347e6d',
    messagingSenderId: '86032851224',
    projectId: 'movie-ef056',
    storageBucket: 'movie-ef056.firebasestorage.app',
    iosClientId: '86032851224-4mbemm1indckn41s5f3ao62afkbfmlk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGXnx_MKtz3jK2rvV8mKxT6ld0oWhYIXM',
    appId: '1:86032851224:web:80bc8704349fa56e347e6d',
    messagingSenderId: '86032851224',
    projectId: 'movie-ef056',
    authDomain: 'movie-ef056.firebaseapp.com',
    storageBucket: 'movie-ef056.firebasestorage.app',
    measurementId: 'G-2GT0ZQPZ24',
  );

}